spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: false
      routes:
        - id: gerenciamento-series
          uri: http://localhost:8081
          predicates:
            - Path=/series/**
        - id: gerenciamento-filme
          uri: http://localhost:8082
          predicates:
            - Path=/filmes/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
